"""refactor structure of backend#3 (review)

Revision ID: 77a19010d1bf
Revises: 4d72f48b9094
Create Date: 2024-10-10 16:50:10.641019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a19010d1bf'
down_revision: Union[str, None] = '4d72f48b9094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
