name: Deploy to Server

env:
  MIN_COVERAGE_REQUIRED: 75

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  python-test-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12

      - name: Install dependencies and setup environments
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          cp default.env .env

      - name: Run tests with coverage
        run: coverage run -m pytest

      - name: Check total coverage
        id: total-coverage
        run: |
          coverage report --format total | python -c 'import sys; current_coverage = int(sys.stdin.read()); is_covered = current_coverage >= '$MIN_COVERAGE_REQUIRED'; print("Coverage is: ", current_coverage); sys.exit(not is_covered)'

  build-and-push-image:
    needs:
      - python-test-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/hepik/animeonix-back:latest
